# CI/CD Pipeline
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2
        
      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Instalar Dependências
        run: |
          pip install -r backend/tests/requirements.txt
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Rodar Testes
        run: |
          export TEST_MODE=True
          pytest backend/tests --disable-warnings
          
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Conectar e fazer deploy no servidor
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu
            
            echo "Atualizando repositório..."
            if [ -d "video-processor" ]; then
              cd video-processor
              git reset --hard
              git pull origin main
            else
              git clone https://github.com/michelleamesquita/video-processor.git
              cd video-processor
            fi
            
            echo "Rodando docker-compose up..."
            docker-compose down
            docker-compose up -d --build
